services:
   _defaults:
      autowire: true
      autoconfigure: true
      public: false
      
   WEBcoast\ProjectTimeline\:
      resource: '../Classes/*'
      exclude: ['../Classes/Domain/Model/*']
